# Generated by Django 2.2 on 2021-01-30 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='caja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epc', models.CharField(max_length=50)),
                ('id_caja', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='conductor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epc', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='registro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=10)),
                ('id_caja', models.CharField(max_length=50)),
                ('movimiento', models.CharField(max_length=10)),
                ('estado', models.CharField(max_length=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='vehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epc', models.CharField(max_length=50)),
                ('placa', models.CharField(max_length=10)),
            ],
        ),
    ]
